# Generated by Django 3.2 on 2023-02-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
    ]
